### ISSUE TITLE
Error when using CC address

### ISSUE THREAD

**Issue by pwaller24** [renevanosnabrugge/SendEmail-BuildTask#15]
I added the task to a build and added a valid email for the To address and another valid email to the CC address.  When the task runs I get this:

System.Net.Mail.SmtpFailedRecipientException: Insufficient system storage. The server response was: 4.5.3 Too many recipients (AS780090) 

What I read indicates that this could mean there is a bad email address being sent in the email.  Removing the CC address allows the build to complete successfully.  

Here is the full log:

2017-12-14T17:53:35.8377411Z ##[debug]Evaluating condition for step: 'Send an email with subject Test email from a build'
2017-12-14T17:53:35.8377411Z ##[debug]Evaluating: succeeded()
2017-12-14T17:53:35.8377411Z ##[debug]Evaluating succeeded:
2017-12-14T17:53:35.8377411Z ##[debug]=> (Boolean) True
2017-12-14T17:53:35.8377411Z ##[debug]Expanded: True
2017-12-14T17:53:35.8377411Z ##[debug]Result: True
2017-12-14T17:53:35.8377411Z ##[section]Starting: Send an email with subject Test email from a build
2017-12-14T17:53:35.8557432Z ==============================================================================
2017-12-14T17:53:35.8557432Z Task         : Send email
2017-12-14T17:53:35.8557432Z Description  : Send an email to 1 or more addresses via the SMTP server you provide
2017-12-14T17:53:35.8557432Z Version      : 1.1.1029
2017-12-14T17:53:35.8557432Z Author       : R. van Osnabrugge
2017-12-14T17:53:35.8557432Z Help         : Version: 1.1.1029. [More information](http://gitub.com/rvanosnabrugge)
2017-12-14T17:53:35.8557432Z ==============================================================================
2017-12-14T17:53:35.8806928Z Preparing task execution handler.
2017-12-14T17:53:36.3107328Z Executing the powershell script: D:\A1\W\_tasks\SendEmail_a41d805b-80c4-4b20-924d-b8d1cca9a43f\1.1.1029\SendMail.ps1
2017-12-14T17:53:36.3137315Z ##[debug]PowerShellHandler.Execute - AddCommand(D:\A1\W\_tasks\SendEmail_a41d805b-80c4-4b20-924d-b8d1cca9a43f\1.1.1029\SendMail.ps1)
2017-12-14T17:53:36.3137315Z ##[debug]PowerShellHandler.Execute - Add inputParameters
2017-12-14T17:53:36.3137315Z ##[debug]PowerShellHandler.Execute - AddParameter(To=xxxxx@xxxxxx.com)
2017-12-14T17:53:36.3137315Z ##[debug]PowerShellHandler.Execute - AddParameter(CC=yyyyy@xxxxxx.com)
2017-12-14T17:53:36.3137315Z ##[debug]PowerShellHandler.Execute - AddParameter(BCC=)
2017-12-14T17:53:36.3137315Z ##[debug]PowerShellHandler.Execute - AddParameter(From=zzzzz@xxxxxx.com)
2017-12-14T17:53:36.3137315Z ##[debug]PowerShellHandler.Execute - AddParameter(Subject=Test email from a build)
2017-12-14T17:53:36.3137315Z ##[debug]PowerShellHandler.Execute - AddParameter(Body=This is a test email sent by a Build Definition.)
2017-12-14T17:53:36.3137315Z ##[debug]PowerShellHandler.Execute - AddParameter(BodyAsHtml=true)
2017-12-14T17:53:36.3146951Z ##[debug]PowerShellHandler.Execute - AddParameter(AddAttachment=false)
2017-12-14T17:53:36.3146951Z ##[debug]PowerShellHandler.Execute - AddParameter(Attachment=)
2017-12-14T17:53:36.3146951Z ##[debug]PowerShellHandler.Execute - AddParameter(SmtpServer=p2es-com.mail.protection.outlook.com)
2017-12-14T17:53:36.3146951Z ##[debug]PowerShellHandler.Execute - AddParameter(SmtpPort=25)
2017-12-14T17:53:36.3146951Z ##[debug]PowerShellHandler.Execute - AddParameter(SmtpUsername=aaaaaaaa@aaaa.com)
2017-12-14T17:53:36.3146951Z ##[debug]PowerShellHandler.Execute - AddParameter(SmtpPassword=VSTS********2017!)
2017-12-14T17:53:36.3146951Z ##[debug]PowerShellHandler.Execute - AddParameter(UseSSL=false)
2017-12-14T17:53:36.3936976Z ##[debug]PowerShellHandler.Execute - Invoke
2017-12-14T17:53:36.4557323Z Input Vars
2017-12-14T17:53:36.4577308Z Send Email To: xxxxxx@xxxxxx.com
2017-12-14T17:53:36.4577308Z Send Email CC: yyyyy@xxxxxx.com
2017-12-14T17:53:36.4577308Z Send Email BCC: 
2017-12-14T17:53:36.4577308Z Subject: Test email from a build
2017-12-14T17:53:36.4577308Z Send Email From: zzzzz@xxxxxx.com
2017-12-14T17:53:36.4587328Z Body as Html?: true
2017-12-14T17:53:36.4587328Z SMTP Server: p2es-com.mail.protection.outlook.com
2017-12-14T17:53:36.4587328Z SMTP Username: aaaaaaaaaa@aaa.com
2017-12-14T17:53:36.4587328Z SMTP Port: 25
2017-12-14T17:53:36.4587328Z Use SSL?: false
2017-12-14T17:53:36.4587328Z Add Attachment?: false
2017-12-14T17:53:36.4597323Z Attachment: 
2017-12-14T17:53:37.7387339Z ##[error]System.Net.Mail.SmtpFailedRecipientException: Insufficient system storage. The server response was: 4.5.3 Too many recipients (AS780090) [CO1NAM04FT052.eop-NAM04.prod.protection.outlook.com]
2017-12-14T17:53:37.7397334Z ##[debug]Processed: ##vso[task.logissue type=error;]System.Net.Mail.SmtpFailedRecipientException: Insufficient system storage. The server response was: 4.5.3 Too many recipients (AS780090) [CO1NAM04FT052.eop-NAM04.prod.protection.outlook.com]
2017-12-14T17:53:37.7397334Z    at System.Net.Mail.SmtpClient.Send(MailMessage message)
2017-12-14T17:53:37.7397334Z    at Microsoft.PowerShell.Commands.SendMailMessage.EndProcessing()
2017-12-14T17:53:37.7397334Z ##[error]PowerShell script completed with 1 errors.
2017-12-14T17:53:37.7407323Z ##[section]Finishing: Send an email with subject Test email from a build

**Comment by renevanosnabrugge** [comment]
cannot reproduce
