### ISSUE TITLE
Failed to process message due to a permanent exception with message Cannot submit message.

### ISSUE THREAD

**Issue by GooseDeer** [renevanosnabrugge/SendEmail-BuildTask#20]
I am getting the following issue when trying to use your task:

```
2018-11-15T15:41:26.9107642Z ##[section]Starting: Email Upcoming Deployment Details
2018-11-15T15:41:26.9370336Z ==============================================================================
2018-11-15T15:41:26.9370659Z Task         : Send email
2018-11-15T15:41:26.9370893Z Description  : Send an email to 1 or more addresses via the SMTP server you provide
2018-11-15T15:41:26.9371148Z Version      : 1.1.1029
2018-11-15T15:41:26.9371346Z Author       : R. van Osnabrugge
2018-11-15T15:41:26.9371594Z Help         : Version: 1.1.1029. [More information](http://gitub.com/rvanosnabrugge)
2018-11-15T15:41:26.9371848Z ==============================================================================
2018-11-15T15:41:26.9763580Z Preparing task execution handler.
2018-11-15T15:41:27.2481914Z Executing the powershell script: C:\vsts\_work\_tasks\SendEmail_a41d805b-80c4-4b20-924d-b8d1cca9a43f\1.1.1029\SendMail.ps1
2018-11-15T15:41:27.5584334Z Input Vars
2018-11-15T15:41:27.5604942Z Send Email To: email1@email.com
2018-11-15T15:41:27.5609098Z Send Email CC: 
2018-11-15T15:41:27.5612865Z Send Email BCC: 
2018-11-15T15:41:27.5616752Z Subject: Test
2018-11-15T15:41:27.5620659Z Send Email From: email2@email.com
2018-11-15T15:41:27.5624370Z Body as Html?: false
2018-11-15T15:41:27.5628170Z SMTP Server: smtp.office365.com
2018-11-15T15:41:27.5631920Z SMTP Username: email3@email.com
2018-11-15T15:41:27.5635836Z SMTP Port: 587
2018-11-15T15:41:27.5639559Z Use SSL?: true
2018-11-15T15:41:27.5643254Z Add Attachment?: false
2018-11-15T15:41:27.5646961Z Attachment: 
2018-11-15T15:41:29.9156161Z ##[error]System.Net.Mail.SmtpException: Transaction failed. The server response was: 5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. ..., 20.52176:140F0E852E00101040000830, 20.50032:140F0E85881710100A000B30, 0.35180:41040000, 255.23226:0A001D30, 255.27962:0A000000, 255.27962:0E000000, 255.31418:0A000000, 16.55847:84000000, 17.43559:0000000098010000000000002A00000000000000, 20.52176:140F0E852E0010105A040000, 20.50032:140F0E85881710105F040000, 0.35180:0201FE67, 255.23226:64040000, 255.27962:0A000000, 255.27962:32000000, 255.17082:DC040000, 0.27745:83040000, 4.21921:DC040000, 255.27962:FA000000, 255.1494:0A006283, 0.37692:02000100, 0.44092:02000100, 0.41232:02000100, 0.60208:02000100, 0.37136:01040480, 0.34608:01040480, 0.55056:01040480, 0.42768:01040480, 0.56112:02000100, 0.52807:02000100, 4.33016:DC040000, 7.40748:010000000000010B02000100, 7.57132:000000000000000002000100, 1.63016:32000000, 4.39640:DC040000, 8.45434:E6FF1F01E7616640B76E67F2806EC1EC02000100, 5.10786...
2018-11-15T15:41:29.9158506Z    at System.Net.Mail.DataStopCommand.CheckResponse(SmtpStatusCode statusCode, String serverResponse)
2018-11-15T15:41:29.9158792Z    at System.Net.Mail.DataStopCommand.Send(SmtpConnection conn)
2018-11-15T15:41:29.9159056Z    at System.Net.ClosableStream.Close()
2018-11-15T15:41:29.9159273Z    at System.Net.Mail.SmtpClient.Send(MailMessage message)
2018-11-15T15:41:29.9159523Z    at Microsoft.PowerShell.Commands.SendMailMessage.EndProcessing()
2018-11-15T15:41:29.9295927Z ##[error]PowerShell script completed with 1 errors.
2018-11-15T15:41:29.9313692Z ##[section]Finishing: Email Upcoming Deployment Details
```

**Comment by renevanosnabrugge** [comment]
Do you run on a hosted agent ? Have you tried another SMTP server ?

What happend if you run the powershell script locally? Or in the build ?

Did iT work before ?

Thanks
Rene

Verstuurd vanaf mijn iPhone

Op 15 nov. 2018 om 18:44 heeft GooseDeerSolutions <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I am getting the following issue when trying to use your task:

2018-11-15T15:41:26.9107642Z ##[section]Starting: Email Upcoming Deployment Details
2018-11-15T15:41:26.9370336Z ==============================================================================
2018-11-15T15:41:26.9370659Z Task         : Send email
2018-11-15T15:41:26.9370893Z Description  : Send an email to 1 or more addresses via the SMTP server you provide
2018-11-15T15:41:26.9371148Z Version      : 1.1.1029
2018-11-15T15:41:26.9371346Z Author       : R. van Osnabrugge
2018-11-15T15:41:26.9371594Z Help         : Version: 1.1.1029. [More information](http://gitub.com/rvanosnabrugge)
2018-11-15T15:41:26.9371848Z ==============================================================================
2018-11-15T15:41:26.9763580Z Preparing task execution handler.
2018-11-15T15:41:27.2481914Z Executing the powershell script: C:\vsts\_work\_tasks\SendEmail_a41d805b-80c4-4b20-924d-b8d1cca9a43f\1.1.1029\SendMail.ps1
2018-11-15T15:41:27.5584334Z Input Vars
2018-11-15T15:41:27.5604942Z Send Email To: email1@email.com<mailto:email1@email.com>
2018-11-15T15:41:27.5609098Z Send Email CC:
2018-11-15T15:41:27.5612865Z Send Email BCC:
2018-11-15T15:41:27.5616752Z Subject: Test
2018-11-15T15:41:27.5620659Z Send Email From: email2@email.com<mailto:email2@email.com>
2018-11-15T15:41:27.5624370Z Body as Html?: false
2018-11-15T15:41:27.5628170Z SMTP Server: smtp.office365.com<http://smtp.office365.com>
2018-11-15T15:41:27.5631920Z SMTP Username: email3@email.com<mailto:email3@email.com>
2018-11-15T15:41:27.5635836Z SMTP Port: 587
2018-11-15T15:41:27.5639559Z Use SSL?: true
2018-11-15T15:41:27.5643254Z Add Attachment?: false
2018-11-15T15:41:27.5646961Z Attachment:
2018-11-15T15:41:29.9156161Z ##[error]System.Net.Mail.SmtpException: Transaction failed. The server response was: 5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. ..., 20.52176:140F0E852E00101040000830, 20.50032:140F0E85881710100A000B30, 0.35180:41040000, 255.23226:0A001D30, 255.27962:0A000000, 255.27962:0E000000, 255.31418:0A000000, 16.55847:84000000, 17.43559:0000000098010000000000002A00000000000000, 20.52176:140F0E852E0010105A040000, 20.50032:140F0E85881710105F040000, 0.35180:0201FE67, 255.23226:64040000, 255.27962:0A000000, 255.27962:32000000, 255.17082:DC040000, 0.27745:83040000, 4.21921:DC040000, 255.27962:FA000000, 255.1494:0A006283, 0.37692:02000100, 0.44092:02000100, 0.41232:02000100, 0.60208:02000100, 0.37136:01040480, 0.34608:01040480, 0.55056:01040480, 0.42768:01040480, 0.56112:02000100, 0.52807:02000100, 4.33016:DC040000, 7.40748:010000000000010B02000100, 7.57132:000000000000000002000100, 1.63016:32000000, 4.39640:DC040000, 8.45434:E6FF1F01E7616640B76E67F2806EC1EC02000100, 5.10786...
2018-11-15T15:41:29.9158506Z    at System.Net.Mail.DataStopCommand.CheckResponse(SmtpStatusCode statusCode, String serverResponse)
2018-11-15T15:41:29.9158792Z    at System.Net.Mail.DataStopCommand.Send(SmtpConnection conn)
2018-11-15T15:41:29.9159056Z    at System.Net.ClosableStream.Close()
2018-11-15T15:41:29.9159273Z    at System.Net.Mail.SmtpClient.Send(MailMessage message)
2018-11-15T15:41:29.9159523Z    at Microsoft.PowerShell.Commands.SendMailMessage.EndProcessing()
2018-11-15T15:41:29.9295927Z ##[error]PowerShell script completed with 1 errors.
2018-11-15T15:41:29.9313692Z ##[section]Finishing: Email Upcoming Deployment Details

**Comment by GooseDeer** [comment]
After looking at it again, I managed to get it working, I was  not using the correct sender email address. This issue was human error.

**Comment by renevanosnabrugge** [comment]
Thanks for reporting back!

Verstuurd vanaf mijn iPhone

Op 16 nov. 2018 om 12:11 heeft GooseDeerSolutions <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


After looking at it again, I managed to get it working, I was not using the correct sender email address. This issue was human error.
