### ISSUE TITLE
Error when no attachments

### ISSUE THREAD

**Issue by samidabeast** [renevanosnabrugge/SendEmail-BuildTask#23]
2019-01-16T20:03:26.5731255Z Add Attachment?: false
2019-01-16T20:03:26.5732906Z Attachment: 
2019-01-16T20:03:26.5969511Z ##[error]System.Management.Automation.MethodInvocationException: Exception calling "ToInt32" with "2" argument(s): "Index was out of range. Must be non-negative and less than the size of the collection.
2019-01-16T20:03:26.5977385Z Parameter name: startIndex" ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
2019-01-16T20:03:26.5977475Z Parameter name: startIndex
2019-01-16T20:03:26.5977527Z    at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
2019-01-16T20:03:26.5977600Z    at System.Convert.ToInt32(String value, Int32 fromBase)
2019-01-16T20:03:26.5977649Z    at CallSite.Target(Closure , CallSite , RuntimeType , String , Int32 )
2019-01-16T20:03:26.5977698Z    --- End of inner exception stack trace ---
2019-01-16T20:03:26.5977773Z    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
2019-01-16T20:03:26.5977850Z    at CallSite.Target(Closure , CallSite , RuntimeType , String , Int32 )
2019-01-16T20:03:26.5977912Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
2019-01-16T20:03:26.5977976Z    at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
2019-01-16T20:03:26.5978030Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-01-16T20:03:28.2449824Z ##[error]PowerShell script completed with 1 errors.

I have 'Add Attachment' unchecked and 'Attachment (absolute path)' blank

**Comment by carolina007** [comment]
We have the same issue. It would be best if the tasks doesn't have AddAttachment checkbox. Code can automatically add attachment with valid file path is give in attachment field.

{
      "name": "AddAttachment",
      "type": "boolean",
      "label": "Add Attachment?:",
      "defaultValue": "false",
      "required": true,
      "groupName": "mailsettings",
      "helpMarkDown": "Indicate if a file will be attached to the email"
    },
